### ISSUE TITLE
[Question] Features differences?

### ISSUE THREAD

**Issue by Insane96** [MinecraftModDevelopment/OreSpawn#130]
I've seen that you can specify "feature" for each vein.

There are 5 different generators (which when not specified uses 'default')
What's the difference between those generation (vein, normal-cloud, precision, clusters)?

**Comment by dshadowwolf** [comment]
"vein" generates actual veins instead of "lodes"
"normal-cloud" generates a "cloud" of single points around a chosen center at the 1 sigma out point from that center using the population data given by the parameters
"precision" generates lodes like "default" but tries to get within 5% of the specified value per chunk
"clusters" uses the same math as "normal-cloud" to find positioning, but does small lodes at each point instead of just a single ore
