### ISSUE TITLE
Setting "feature" to "vein" crashes the game on world creation.

### ISSUE THREAD

**Issue by Insane96** [MinecraftModDevelopment/OreSpawn#131]
orespawn.json: https://pastebin.com/UyG7tAJU

Crash report: https://pastebin.com/tBiLpfpK

I've noticed that the oob changes every crash.

**Comment by dshadowwolf** [comment]
Check the docs. Vein has different parameters. This is a bug, but... there is a reason that nothing beyond "default" is documented

**Comment by Insane96** [comment]
Uhm, ok then. I see double the parameters.
What's "wander" for?

And another question, "chance" is weight based or percentage based?

**Comment by dshadowwolf** [comment]
...and I just realized you're working with the version that has the broken vein code... I have some work to do - the vein generator has been updated in -dev to fix it being brain-dead and "wander" has been removed

Chance is a probability - in currently released versions it builds a flattened segment tree and selects a node at random

**Comment by Insane96** [comment]
I'm checking build 140
But I have a few questions
"minHeight", "maxHeight", "variation", "frequency" and "size" are like the default feature?
What are "minAttempts", "maxAttempts" and "length" for?

~~And what are the parameters for "normal-cloud"? The default ones seems to spawn 1 block only.~~
Nevermind, checked the class and got the parameters, but now I'm getting this log spam: https://pastebin.com/V2MpH0T1 with this orespawn.json: https://pastebin.com/SKNwbcDg

**Comment by Insane96** [comment]
It's been a while now. Don't want to bother but any news?

**Comment by dshadowwolf** [comment]
Sorry - I burned out bad while working on the new startup and registration code for *Metals/MMDLib. Most of this should be fixed in -dev and is j7st being held back for a release in sync with *Metals -rc1/-beta6

As to the parameters... some of them are alternates for some other bits - "minAttempts" and "maxAttempts" are the minimum and maximum number of times the code will try to place a load.  "Frequency" is, for default (and maybe a few others), how often a feature will generate. Other parameters are similar...

As to the error... you've found some debugging I missed when cleaning up prior to release - I'd added that to alert me to a vein being generated.

**Comment by dshadowwolf** [comment]
As far as I can tell - and from the fact that the code has been reworked quite a bit - this has been fixed. Closing
