### ISSUE TITLE
I'm having an issue with some sort of world gen error between orespawn and chromaticraft

### ISSUE THREAD

**Issue by adlwar137** [MinecraftModDevelopment/OreSpawn#133]
Crash: https://pastebin.com/gKmpaJ2z
can't post log because the log is to big for pastebin and I don't have premium.

**Comment by dshadowwolf** [comment]
Looking at that crash log I'd say the issue seems to be Chromaticraft doing things improperly, but I will have to look at the Chromaticraft source to be certain. It might also be an edge-case in OreSpawn related to the new config handling code, as that has some areas that didn't get a lot of testing. I'll look in the morning.

**Comment by dshadowwolf** [comment]
Wait... okay, yeah, umm.... hate to have to say this, but... You've reported something for a different mod completely. This is for MMD OreSpawn - a world generation mod that acts to provide ore generation for other mods, similar to CoFHWorld. This is not the mod that adds the "dangerzone", ore trees and a lot of other stuff. For that you'll want to go [here](http://www.orespawn.com/) and ask for help.
