### ISSUE TITLE
Crash when changing OreSpawn values

### ISSUE THREAD

**Issue by breadguyyy** [MinecraftModDevelopment/OreSpawn#157]
this crash keeps happening when i change the size and rarity of ore veins in an attempt to make veins a little bigger and less common. Not sure whats causing it, i'm probably messing something up, but the logs dont point me to anything that i might be doing wrong.
crashlog: https://paste.dimdev.org/ikulipecex.mccrash

**Comment by breadguyyy** [comment]
hang on.... it has something to do with me trying to spawn chisel limestone and marble with orespawn. i just copy and pasted the granite section and replaced the granite parts with limestone and marble. still cant find anything wrong with it....

**Comment by dshadowwolf** [comment]
You found a valid bug - I'm used to using ``%u`` for unsigned in C and C++, Java does not have (technically) unsigned types, so its formatted string stuff only has ``%d`` (integer, decimal format). However you ran into it because you've got an error in your config - specifically one involving use of the ``state`` property. Note that if the block does not have state, don't include the piece, as it will break. :)

**Comment by breadguyyy** [comment]
interesting, so for instance if i wanted chisel marble to spawn id put 
{"name": "chisel:marble2:7", "chance": 100,} 
as opposed to
{"name": "chisel:marble2", "chance": 100 ,"state": "variant=7"}
or
{"name": "chisel:marble2", "chance": 100 ,"state": "variant=raw"}?

still learning this whole thing lol. thanks for the help!

**Comment by dshadowwolf** [comment]
nah, you'd do:
```json
{ "name": "chisel:marble2", "metaData": 7, "chance": 100 }
```
or
```json
{ "name": "chisel:marble2", "chance": 100, "state": "variant=marble/raw" }
```
(this last one is a guess based on looking at the blockstate json in the Chisel source - let me add Chisel to a test instance and see...)

**Comment by dshadowwolf** [comment]
Okay did a test, found this in my instance logs:
```
Asked to spawn chisel:marble2[variation=7]
```
This would mean that the actual config line for the block would be:
```json
{ "name": "chisel:marble2", "chance": 100, "state": "variation=7" }
```
The difference is that they use "variation" in Chisel instead of "variant"

**Comment by breadguyyy** [comment]
wow yeah i would have never guessed that, thank you so much, ill go test it right now

**Comment by dshadowwolf** [comment]
well... there is (apparently) still a major bug elsewhere causing issues, but... thats neither here nor there (I can't figure out WTF is going wrong there, sadly...) as it doesn't (directly) impact your issue. I might have to add a "/os3_hand" command that gives the block in hand as output, in the format that OS3 expects.

**Comment by breadguyyy** [comment]
fortunately i havent been having any other issues other than veins getting cut off at chunk borders pretty often, but I'm not sure how to remedy that one from my end

**Comment by dshadowwolf** [comment]
...that, sadly, is because we only have a 4 chunk zone loaded during world-gen - its how Minecraft does things. If you trigger anything beyond those 4 to be loaded, that is "Cascading Chunk Gen Lag" and it can kill servers pretty easily. And yeah... the vein generator has a small issue that I can't figure out how to get around with hitting those chunk borders - it cannot, realistically, continue pathing to build the vein when its going into unloaded-chunk territory. Sorry :(

**Comment by breadguyyy** [comment]
no problem my friend, its not really noticeable unless i use something like worldstripper, and its better than a bunch of lag obviously

thank you again for all the help!

**Comment by dshadowwolf** [comment]
apparently already fixed in -dev
