### ISSUE TITLE
1.7.10 build?

### ISSUE THREAD

**Issue by Kerbinator-Fras** [MinecraftModDevelopment/OreSpawn#177]
Build one thx

**Comment by KiriCattus** [comment]
1.7.10 is HIGHLY unsupported in the modding community (among modders) I don't think there are any plans to support that version at the moment.

**Comment by dshadowwolf** [comment]
Due to technical changes on the internet (things like TLS1.0 and such becoming unsupported) it is almost impossible to actually setup a working build environment for any version of Minecraft older than 1.8. Beyond that, 1.7.10 is extremely old and not within any of the current teams knowledge and skill. Beyond that... if you need world-gen support like MMD OreSpawn provides in an old version of Minecraft, such as 1.7.10, I'd suggest looking at CoFHWorld - which does exist for 1.7.10
